name = "MlModelDeploy"
uuid = "ef3c1a0d-2b11-4b0e-a16a-9edae2908dfa"
authors = ["sebkaz <seba@sebastianzajac.pl>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
